### ISSUE TITLE
Error message after estimate_npmetric_erf

### ISSUE THREAD

**Issue by MatteoCorsiUnige** [NSAPH-Software/CausalGPS#216] opened 2023-04-20 15:21 UTC
I get the following message while trying to estimate the non parametric exposure-response function.

`Error in checkForRemoteErrors(val) : 
  one node produced an error: length(xeval) < .maxEvalPts is not TRUE`

The error appears to be linked with the number of observations: it goes away with very large trimming and with smaller synthetic samples. The number of nodes varies with the number of threads. An example to be reproduced is reported below:

```
mydata <- generate_syn_data(sample_size = 10000) 
pseudo_pop <- generate_pseudo_pop(mydata$Y,
                                  mydata$treat,
                                  mydata[c("cf1","cf2","cf3","cf4","cf5","cf6")],
                                  ci_appr = "matching",
                                  sl_lib = c("m_xgboost"),
                                  params = list(xgb_nrounds=c(10,20,30),
                                   xgb_eta=c(0.1,0.2,0.3)),
                                  nthread = 1,
                                  covar_bl_method = "absolute",
                                  covar_bl_trs = 0.1,
                                  covar_bl_trs_type= "mean",
                                  max_attempt = 1,
                                  matching_fun = "matching_l1",
                                  delta_n = 1,
                                  scale = 0.5)
erf_val <- estimate_npmetric_erf(pseudo_pop$pseudo_pop$Y,
                                 pseudo_pop$pseudo_pop$w,
                                 pseudo_pop$pseudo_pop$counter_weight,nthread=1,
                                 bw_seq=seq(0.2,2,0.2),
                                 w_vals = seq(2,20,0.5))
```

This results in the error code, but if I change sample_size to 1000 it goes away.

Thanks in advance,
Matteo Corsi

**Comment by Naeemkh** [comment] 2023-04-20 18:43
Hello @MatteoCorsiUnige, we appreciate you pointing this out. The issue appears to stem from the locpol package, particularly from this function:

https://github.com/cran/locpol/blob/3da83cceb2bd81442627b6fd49429867fb500357/R/locpol.R#L517

I'll investigate further and update you once I have more information. @wxwx1993, any idea?

**Comment by Naeemkh** [comment] 2023-04-20 18:56
Simpler reproducible example:

```
n = 10000
Y = runif(n, min = 0, max = 10)
w = runif(n, min = 0, max = 10)
weight = runif(n, min = 0, max = 4)
xeval = seq(1, 9, 0.5)
h_opt = 0.4

data <- data.frame(Y = Y,
                   w = w)
res <- locpol::locpol(formula = Y ~ w,
                      data = data1,
                      bw = h_opt,
                      weig = weight,
                      xeval = xeval,
                      kernel = locpol::gaussK)
```

**Comment by wxwx1993** [comment] 2023-04-20 18:58
This is a long-standing question with the locpol R package. I have submitted ticket to the developers of locpol, but have not heard back.

**Comment by Naeemkh** [comment] 2023-04-20 19:00
Thanks, @wxwx1993. Should we return the Kernel Smoothing option back?

**Comment by wxwx1993** [comment] 2023-04-20 19:01
The key drawback of Kernel Smoothing is that they do not allow weights in functions unless we want to hand write it. What do you think, I can ask if anyone is interested to implement it as a master project.

**Comment by Naeemkh** [comment] 2023-04-20 19:27
Sounds good to me.

**Comment by Naeemkh** [comment] 2023-04-24 18:21
Hi @MatteoCorsiUnige

One workaround can be downloading the locpol code from its CRAN mirror: https://github.com/cran/locpol 
and modify this line: https://github.com/cran/locpol/blob/3da83cceb2bd81442627b6fd49429867fb500357/R/locpol.R#L365
Then install the package locally. 
Closing this issue because it is not directly related to the CausalGPS package. Please feel free to open any new issues or reopen this issue if the problem is not resolved.

**Closed by Naeemkh** 2023-04-24 18:21 UTC
Labels: bug, help wanted

**Comment by luca-merlo** [comment] 2023-05-19 22:58
Hi @Naeemkh,
I have encountered this problem a lot in our project with @wxwx1993. The best option is still to install the locpol package locally modifying the line you mentioned or is there another quicker solution?

Many thanks,
Luca

**Comment by Naeemkh** [comment] 2023-05-22 21:59
Please install locpol using the following command:
```r
remotes::install_github("NSAPH-Software/locpol", reference="master")
```
